return {
  {
    key = "ev_1512",
    label = "1512 EVS",
    type = "choice",
    default = "off",
    choices = { { "OFF", "off" }, { "NPC", "npc" }, { "PLAYER", "player" }, { "BOTH", "both" } },
    description = "OFF: classic 252-per-stat, 510-total EV limits. NPC: enemy trainer mons may hold 1512 total. PLAYER: your mons may hold 1512 total. BOTH: everyone may.",
  },
  {
    key = "item_reuse",
    label = "ITEM REUSE",
    type = "toggle",
    default = true,
    description = "ON (default): held items consumed or lost in battle are back after battle ends. OFF: vanilla.",
  },
  {
    key = "exp_share",
    label = "EXP SHARE",
    type = "choice",
    default = "off",
    choices = { { "OFF", "off" }, { "GENERATION 1", "gen1" }, { "GENERATION 2", "gen2" }, { "GENERATION 3", "gen3" }, { "GENERATION 6", "gen6" } },
    description = "Party-wide experience: GEN 1 Exp. All, GEN 2 held share shown twice, GEN 3 same split shown once, GEN 6 battlers full and bench half. OFF leaves the award alone.",
  },
  {
    key = "doubles",
    label = "DOUBLES",
    type = "toggle",
    default = false,
    description = "ON: trainers with 2 or more Pokemon force a native double battle. OFF: vanilla.",
  },
  {
    key = "rematches",
    label = "REMATCHES",
    type = "toggle",
    default = false,
    description = "ON: talking to a beaten trainer asks for a rematch; wins pay prize money. OFF: vanilla.",
  },
  {
    key = "lv_adapt",
    label = "LV ADAPT",
    type = "choice",
    default = "vanilla",
    choices = { { "VANILLA", "vanilla" }, { "-5 LVL", "minus5" }, { "+5 LVL", "plus5" }, { "+10 LVL", "plus10" }, { "0", "zero" } },
    description = "Adapt trainer teams to your strongest party mon: -5/+5/+10 around it, 0 exactly at it, keeping each team's own level gaps. VANILLA leaves trainers alone.",
  },
  {
    key = "difficulty",
    label = "DIFFICULTY",
    type = "choice",
    default = "vanilla",
    choices = { { "VANILLA", "vanilla" }, { "EASY", "easy" }, { "NORMAL", "normal" }, { "HARD", "hard" }, { "VERY HARD", "veryhard" }, { "HELL", "hell" } },
    description = "Enemy IVs/EVs: EASY 0, NORMAL 25%, HARD 50%, VERY HARD 75%, HELL 100% (31 IV, 252 per stat when 1512 EVS covers enemies). VANILLA leaves trainers alone.",
  },
}
